### ISSUE TITLE
Register-HPEiLORemoteSupportSetting cmdlet

### ISSUE THREAD

**Issue by ygiri1** [HewlettPackard/PowerShell-ProLiant-SDK#64]
if there is a direct connection and you don't have any proxy to connect to the internet for the register server, still would require proxy details. below is the error.

Register-HPEiLORemoteSupportSetting : [xxxxxxxxxxxx]: HPEPassportUserID, HPEPassportPassword, WebProxyServer, WebProxyPort must be provided together.
At line:1 char:1
+ Register-HPEiLORemoteSupportSetting -Connection $HPEconnection -Inter ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [Register-HPEiLORemoteSupportSetting], Exception
    + FullyQualifiedErrorId : HPE.iLO.Cmdlet.RegisterHPEiLORemoteSupportSetting

**Comment by hp-powershell** [comment]
Hi ,

Thanks for writing to us. 

we would require the below information
1. Kindly enable-hpeilolog and execute the steps and provide us the log file 
2. what are the Server details and iLO FW details
3. Has the same operation worked without any error from the GUI of the server 
4. Is this the same behavior on all the servers you try this operation on?

Thanks & Regards,
Powershell Team

**Comment by ygiri1** [comment]
here is the log

2021-03-31 18:01:27,302 INFO - [Connect-HPEiLO][XXXServer001][ProcessiLOXmlData]: XML Reply on: Reading iLO xml data
2021-03-31 18:01:27,304 INFO - [Connect-HPEiLO][XXXServer001][ProcessiLOXmlData]: iLO FirmwareVersion: iLO5 v2.35 
2021-03-31 18:01:27,305 INFO - [Connect-HPEiLO][XXXServer001][GetServerInfoFromProductName]: Product Name: ProLiant DL360 Gen10
2021-03-31 18:01:28,967 INFO - [Connect-HPEiLO][XXXServer001][CreateConnection]: Creating connection for connection type(s): Redfish
2021-03-31 18:01:28,968 INFO - [Connect-HPEiLO][XXXServer001][Redfish][CreateConnection]: Establishing connection.
2021-03-31 18:01:35,423 INFO - [Connect-HPEiLO][XXXServer001][Redfish][CreateUsernamePasswordConnection]: Received response for create connection request.
2021-03-31 18:01:37,338 INFO - [Connect-HPEiLO][XXXServer001][Redfish][CreateUsernamePasswordConnection]: Connection established.
2021-03-31 18:01:37,342 INFO - [Connect-HPEiLO][XXXServer001][CreateConnection]: Connection established for connection type(s): Redfish
2021-03-31 18:01:52,402 INFO - [Register-HPEiLORemoteSupportSetting][XXXServer001][ValidateCmdletRecord]: Begin
2021-03-31 18:01:52,403 INFO - [Register-HPEiLORemoteSupportSetting][XXXServer001][ValidateCmdletRecord]: Getting username and password if credential object is passed.
2021-03-31 18:01:52,405 ERROR - [Register-HPEiLORemoteSupportSetting][XXXServer001]: 

ExceptionMessage:HPEPassportUserID, HPEPassportPassword, WebProxyServer, WebProxyPort must be provided together..
InnerException:.
StackTrace:   at HPE.iLO.Cmdlet.RegisterHPEiLORemoteSupportSetting.ValidateCmdletRecord(CmdletRecord cmdletRecord)
2021-03-31 18:04:03,759 INFO - [Register-HPEiLORemoteSupportSetting][XXXServer001][ValidateCmdletRecord]: Begin
2021-03-31 18:04:03,760 INFO - [Register-HPEiLORemoteSupportSetting][XXXServer001][ValidateCmdletRecord]: Getting username and password if credential object is passed.
2021-03-31 18:04:03,763 ERROR - [Register-HPEiLORemoteSupportSetting][XXXServer001]: 

ExceptionMessage:HPEPassportUserID, HPEPassportPassword, WebProxyServer, WebProxyPort must be provided together..
InnerException:.
StackTrace:   at HPE.iLO.Cmdlet.RegisterHPEiLORemoteSupportSetting.ValidateCmdletRecord(CmdletRecord cmdletRecord)


with GUI, I don't see any issues with easy registration and the Behaviour is across all Proliant Server we have a mix of Gen 9 and Gen 10 Servers. Currently, on Gen 10 Servers this isn't working. Gen 9 isn't supported with this module which I agree 

ILO firmware is running with  > 2.0

**Comment by hp-powershell** [comment]
Hi,

Thanks for the details. 
We had a discussion with iLo Team to see why we had mandated the parameters earlier. 

As per our discussion, your suggestion of this being issue is correct. We have raised a tracking issue for the same . We will address this in our point release next month. 

Thanks for your help in reporting it.

Thanks & Regards,
Powershell Team

**Comment by hp-powershell** [comment]
Hi ,

Kindly check on latest build of our hpeilocmdlets which is 3.3 . 

if any issue found kindly raise a ticket . 

Thanks & Regards,
Powershell Team
